# Generated by Django 2.0 on 2019-12-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191217_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='', max_length=25, primary_key=True, serialize=False),
        ),
    ]
