# Generated by Django 2.0 on 2019-12-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191217_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False),
        ),
    ]
