# Generated by Django 2.0 on 2019-12-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191219_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='opex',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='revenue',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
