# Generated by Django 2.0 on 2019-12-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hourly_Labor_Cost_1', models.IntegerField()),
                ('Hourly_Labor_Cost_2', models.IntegerField()),
                ('Hourly_Labor_Cost_3', models.IntegerField()),
                ('Labor_Hours_Avail_1', models.IntegerField()),
                ('Labor_Hours_Avail_2', models.IntegerField()),
                ('Labor_Hours_Avail_3', models.IntegerField()),
                ('Product_1_USP', models.IntegerField()),
                ('Product_1_UC', models.IntegerField()),
                ('Product_1_S1', models.IntegerField()),
                ('Product_1_S2', models.IntegerField()),
                ('Product_1_S3', models.IntegerField()),
                ('Product_1_Min', models.IntegerField()),
                ('Product_1_Max', models.IntegerField()),
                ('Product_2_USP', models.IntegerField()),
                ('Product_2_UC', models.IntegerField()),
                ('Product_2_S1', models.IntegerField()),
                ('Product_2_S2', models.IntegerField()),
                ('Product_2_S3', models.IntegerField()),
                ('Product_2_Min', models.IntegerField()),
                ('Product_2_Max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=25)),
                ('raw_material', models.CharField(default='', max_length=25)),
                ('product', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
