# Generated by Django 2.0 on 2020-01-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191220_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='input_val_ass',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='input_val_prod',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='input_val_rm',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
